/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 ./plant.glb -t 
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Circle006: THREE.Mesh;
    Circle006_1: THREE.Mesh;
  };
  materials: {
    MI_MZRa_Monstera_B02a: THREE.MeshStandardMaterial;
    MI_MZRa_Monstera_B02b: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/plant.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle006.geometry}
        material={materials.MI_MZRa_Monstera_B02a}
      />
      <mesh
        geometry={nodes.Circle006_1.geometry}
        material={materials.MI_MZRa_Monstera_B02b}
      />
    </group>
  );
}

useGLTF.preload('/plant.glb');
