/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 ./toy-car.glb -T -t 
Files: ./toy-car.glb [1.76MB] > toy-car-transformed.glb [500.23KB] (72%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Cube011: THREE.Mesh
    Sphere: THREE.Mesh
  }
  materials: {
    PaletteMaterial003: THREE.MeshPhysicalMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial004: THREE.MeshPhysicalMaterial
    PaletteMaterial005: THREE.MeshPhysicalMaterial
    PaletteMaterial006: THREE.MeshPhysicalMaterial
    PaletteMaterial007: THREE.MeshPhysicalMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/toy-car-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry} material={materials.PaletteMaterial003} position={[0, 1.45, 0]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.PaletteMaterial001} position={[0, 1.449, 0]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.PaletteMaterial002} position={[-2.154, 0.704, 0]} scale={[0.056, 0.114, 1]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.PaletteMaterial004} position={[-1.811, 1.041, -1.012]} rotation={[0, -0.564, 0]} scale={[0.116, 0.116, 0.05]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.PaletteMaterial005} position={[-1.869, 1.041, -0.869]} rotation={[0, -0.274, 0]} scale={[0.116, 0.116, 0.101]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials.PaletteMaterial006} position={[-1.908, 1.041, -0.706]} rotation={[0, -0.148, 0]} scale={[0.116, 0.116, 0.05]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.PaletteMaterial007} position={[2.332, 1.02, 0.865]} scale={1.468} />
    </group>
  )
}

useGLTF.preload('/toy-car-transformed.glb')
